site_name: Yash Shah
theme:
  name: shadcn

plugins:
  - blog

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

hooks:
  - hooks/typst_math.py

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - overrides/extra-javascript/copy-math.js

