site_name: Yash Shah
theme:
  name: shadcn

plugins:
  - blog
  - search
  - excalidraw
  - mkdocstrings

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition:
  - codehilite:
  - fenced_code:
  - footnotes:
  - extra:
  - pymdownx.blocks.details:
  - pymdownx.tabbed:
  - pymdownx.blocks.tab:
      combine_header_slug: true
      separator: ___
  - pymdownx.progressbar:
  - pymdownx.snippets:
  - pymdownx.arithmatex:
      generic: true
  - shadcn.extensions.echarts.alpha:

hooks:
  - hooks/typst_math.py

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - overrides/extra-javascript/copy-math.js

